import { chromium } from "playwright";
const browser = await chromium.launch({ args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on("pageerror", (e) => console.log("PAGEERROR", e.message));
await page.goto("http://127.0.0.1:8080/", { waitUntil: "networkidle" });
await page.waitForTimeout(700);
await page.getByRole("button", { name: /enter the substrate/i }).click();
await page.waitForFunction(() => typeof window.__setScene === "function");
await page.waitForTimeout(2500);
await page.evaluate(() => window.__setScene(22));
await page.waitForTimeout(2500);
await page.screenshot({ path: "/workspace/screenshots/fix-referee.png" });
console.log("canvas", await page.locator("canvas").count(), "bytes later");
const worthy = page.getByRole("button", { name: /Worthy Emergence/i }).first();
if (await worthy.count()) await worthy.click();
await page.waitForTimeout(1200);
await page.screenshot({ path: "/workspace/screenshots/fix-referee-worthy.png" });
await browser.close();
console.log("done");
